#!/bin/sh
#
# udak - small implementation of Debian Archive Kit
#
# Copyright (C) 2009 Mikhail Gusarov <dottedmag@dottedmag.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

[ -f udak.conf ] && . ./udak.conf 2>/dev/null && PATH=.:$PATH \
    || /etc/udak/udak.conf

EMAIL="$1"
CHANGES="$2"

TMPDIR=$(mktemp -d)
clean() {
    rm -rf "$TMPDIR"
}
trap clean 0 INT QUIT

udak "$UDAK_INCOMING/$CHANGES" >"$TMPDIR/log" 2>&1

if [ $? -eq 0 ]; then
    RESULT="SUCCESS"
else
    RESULT="FAILED"
fi

mail -a "From: $UDAK_FROM_MAIL" "$EMAIL" -s "$RESULT: injecting "$(basename "$CHANGES") < "$TMPDIR/log"

udak-dcmd rm "$UDAK_INCOMING/$CHANGES"
