#!/bin/sh
#
# udak - small implementation of Debian Archive Kit
#
# Copyright (C) 2009 Mikhail Gusarov <dottedmag@dottedmag.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
set -e

if [ $# -ne 1 ]; then
    echo "Usage: $0 <config>"
    exit 1
fi

if expr "$1" : / >/dev/null; then
    CONF="$1"
else
    CONF=$(pwd)/"$1"
fi

. $CONF

LOCK=$UDAK_INCOMING/
lockfile-create -q --retry 0 $LOCK || exit 0
lockfile-touch $LOCK &
LF=$!

rmlock() {
  RET=$?
  kill $LF ||:
  lockfile-remove $LOCK ||:
  return $RET
}
trap rmlock 0 HUP PIPE INT QUIT TERM

inoticoming --foreground --initialsearch \
  "$UDAK_INCOMING" --suffix .changes --chdir "$UDAK_INCOMING" \
  udak-mail "$CONF" {} \;
