#!/bin/sh -e

#
# Checks the signature on given .changes file according to the repository rules.
#

[ -f udak.conf ] && . ./udak.conf 2>/dev/null && PATH=.:$PATH \
    || /etc/udak/udak.conf

gpgv --keyring "$UDAK_KEYRING" "$1"
