#!/bin/sh

[ -f udak.conf ] && . ./udak.conf 2>/dev/null && PATH=.:$PATH \
    || /etc/udak/udak.conf

exec inoticoming \
  --foreground \
  "$UDAK_INCOMING" \
  --suffix .changes udak-send-mail "$UDAK_MAIL" {} \;
