#!/bin/sh
#
# udak - small implementation of Debian Archive Kit
#
# Copyright (C) 2009 Mikhail Gusarov <dottedmag@dottedmag.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

if [ $# -ne 2 ]; then
    echo "Usage: $0 <config> <changes file>"
    exit 1
fi

. $1
CHANGES="$2"

# Moving .changes and associated files to temporary place

TMPDIR=$(mktemp -d)
dcmd mv "$UDAK_INCOMING/$CHANGES" "$TMPDIR"

C=$(basename "$CHANGES")

if OUT=$(udak "--config-file=$1" "$TMPDIR/$CHANGES" 2>&1); then
    RESULT="udak"
else
    RESULT="udak:FAIL"
fi

SUBJ="$RESULT: injecting $C"

echo "$OUT" | mail -a "From: $UDAK_FROM_MAIL" "$UDAK_MAIL" -s "$SUBJ"

rm -rf "$TMPDIR"
