#!/bin/sh
#
# udak - small implementation of Debian Archive Kit
#
# Copyright (C) 2009 Mikhail Gusarov <dottedmag@dottedmag.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

[ -f udak.conf ] && . ./udak.conf 2>/dev/null && PATH=$(pwd):$PATH \
    || . /etc/udak/udak.conf

EMAIL="$1"
CHANGES="$2"

C=$(basename "$CHANGES")

if OUT=$(udak "$UDAK_INCOMING/$CHANGES" 2>&1); then
    RESULT="udak"
else
    RESULT="udak:FAIL"
fi

SUBJ="$RESULT: injecting $C"

echo "$OUT" | mail -a "From: $UDAK_FROM_MAIL" "$EMAIL" -s "$SUBJ"

udak-dcmd rm -f "$UDAK_INCOMING/$CHANGES"
