#!/bin/sh
#
# udak - small implementation of Debian Archive Kit
#
# Copyright (C) 2009 Mikhail Gusarov <dottedmag@dottedmag.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

#
# .changes file upload to repository.
#

while true; do
    case "$1" in
        --config-file=*)
            CONF_ARG="$1"
            CONFIG_FILE=${1#--config-file=}
            shift;;
        *)
            break;;
    esac
done

if [ -n $CONFIG_FILE ]; then
    . $CONFIG_FILE
else
    [ -f udak.conf ] && . ./udak.conf 2>/dev/null && PATH=$(pwd):$PATH \
        || . /etc/udak/udak.conf
fi

for changefile in "$@"; do
    if ! udak-checksig $CONF_ARG "$changefile"; then
        STOP=1
    fi
done

if [ x$STOP = x1 ]; then
    echo "STOP: rejecting upload due to missing signatures"
    exit 1
fi

if ! udak-addchanges $CONF_ARG "$@"; then
    exit 1
fi

udak-regenerate $CONF_ARG
